ranks:
  A:
    price: 0 # Does not matter on the first rank, as it's what you start with.
    permissions:
      - 'essentials.warp.a'
  B:
    price: 10000
    permissions:
      - 'essentials.warp.b'
  C:
    price: 25000
    permissions:
      - 'essentials.warp.c'